export const queryKey = {
    MY_COLLECTIONS: 'my-collections',
    MY_NFTS: 'my-nfts',
    TOP_CREATORS: 'top-creators',
    TRENDING: 'trending',
    MY_TRANSACTIONS: 'my-transactions',
    FAVORITES: 'favorites',
    TICKET: 'ticket',
    TICKETS: 'tickets',
    COLLECTIONS: 'collections',
    TOPCOLLECTIONS: 'topcollections',
    TRENDINGCOLLECTIONS: 'trendingcollections',
    ALLTOPCOLLECTIONS: 'alltopcollections',
    ALLTRENDINGCOLLECTIONS: 'alltrendingcollections',
    ALLTOPCOLLECTIONSPRICE: 'alltopcollectionsprice',
    NFTS: 'nfts',
    ALLNFTS: 'allnfts',
    BLOG: 'blog',
    BLOG_POST: 'blog-post',
    PAGE_DATA: 'page-data',
}